---
services:
  ark-server:
    image: indifferentbroccoli/ark-server-docker
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ark-server
    stop_grace_period: 30s
    ports:
      - 7777:7777/udp
      - 27015:27015/udp
      - 27020:27020/tcp
    env_file:
      - .env
    volumes:
      - ./steamcmd/ark:/home/steam/steamcmd/ark
      - ./ark-backups:/home/steam/ark-backups
